const categories = {
    "AA": "Abstract Algebra",
    "AG": "Algebraic Geometry",
    "AT": "Algebraic Topology",
    "CA": "Commutative Algebra",
    "CP": "Computer Algebra",
    "CT": "Category Theory",
    "DG": "Differential Geometry",
    "DT": "Deformation Theory",
    "FA": "Functional Analysis",
    "GT": "Group Theory",
    "HA": "Homological Algebra",
    "HT": "Homotopy Theory",
    "LA": "Linear Algebra",
    "MT": "Measure Theory",
    "NT": "Number Theory",
    "RT": "Representation Theory",
    "TO": "Topology",
    "UN": "Uncategorized"
};
