const categories = {
    "AA": "Algebra",
    "AG": "Algebraic Geometry",
    "AT": "Algebraic Topology",
    "CA": "Complex Analysis",
    "CO": "Combinatorics",
    "CP": "Computer Algebra",
    "CT": "Category Theory",
    "DG": "Differential Geometry",
    "DT": "Deformation Theory",
    "FA": "Functional Analysis",
    "GM": "General",
    "GT": "Group Theory",
    "HA": "Homological Algebra",
    "HT": "Homotopy Theory",
    "LA": "Linear Algebra",
    "LO": "Logic",
    "MT": "Measure Theory",
    "NT": "Number Theory",
    "RT": "Representation Theory",
    "ST": "Set Theory",
    "TO": "Topology",
    "UN": "Uncategorized"
};
