data = {
    "AG": [ "algebraic-geometry.tex",
            "log-geometry.tex",
            "sheaves.tex",
            "stacks.tex" ],
    "AT": [ "algebraic-topology.tex" ],
    "CA": [ "commutative-algebra.tex",
            "modules.tex",
            "fields.tex",
            "tensor-algebra.tex" ],
    "CP": [ "computer-algebra.tex" ],
    "CT": [ "category-theory.tex",
            "higher-category-theory.tex" ],
    "DG": [ "differential-geometry.tex" ],
    "DT": [ "deformation-theory.tex" ],
    "GT": [ "group-theory.tex" ],
    "HA": [ "homological-algebra.tex",
            "triangulated-categories.tex",
            "derived-categories.tex" ],
    "LA": [ "linear-algebra.tex" ],
    "NT": [ "number-theory.tex" ],
    "TO": [ "topology.tex" ],
    "UN": [ "uncategorized.tex" ]
}
